C A SET OF SURVEY DATA CONTAINS THE AGE AND WEIGHT OF THE
C RESPONDENTS TOGETHER WITH A CODE TO INDICATE THEIR SEX
C (0 = MALE, 1 = FEMALE). PROGRAM READS THE NUMBER OF PEOPLE
C IN THE SURVEY AND THEN CALCULATES THE AVERAGE WEIGHT
C OF THE MEN BETWEEN AGES 21 AND 35 (INCLUSIVE)
C 1 READ NUMBER OF PEOPLE (N)
C 2 INITIALISE SUMS OF WEIGHTS AND PEOPLE TO ZERO
C 3 REPEAT N TIMES
C   3.1 READ AGE,WEIGHT AND SEX CODE
C   3.2 IF MALE AND AGED BETWEEN 21 AND 35 THEN
C        3.2.1 ADD WEIGHT TO SUM OF WEIGHTS
C        3.2.2 ADD ONE TO SUM OF PEOPLE
C 4 CALCULATE AND PRINT THE AVERAGE WEIGHT   
      PROGRAM AVWT
C SP IS THE SUM OF PEOPLE
C SW IS THE SUM OF WEIGHTS
      INTEGER N,SP,AGE,SEX,I
      REAL SW,WT
      PRINT *,'########################################'
      PRINT *, 'THIS PROGRAM READS THE NUMBER OF PEOPLE',
     +' IN THE SURVEY AND THEN CALCULATES THE AVERAGE WEIGHT',
     +' OF THE MEN BETWEEN AGES 21 AND 35 (INCLUSIVE).'
      PRINT *, 'SURVEY DATA CONTAINS THE AGE AND WEIGHT OF THE',
     +' RESPONDENTS TOGETHER WITH A CODE TO INDICATE THEIR SEX',
     +' (0 = MALE, 1 = FEMALE)'
      PRINT *,'########################################'
      PRINT *, 'N. OF PEOPLE IN THE SURVEY?'
      READ *,N
      SW = 0.0
      SP = 0
      DO 10,I=1, N
      PRINT *, 'READING AGE,WEIGHT,SEX FOR PERSON',I
        READ *,AGE,WT,SEX
        IF ((AGE.GE.21) .AND. (AGE.LE.35) .AND. (SEX.EQ.0)) THEN
            SW = SW + WT
            SP = SP + 1
        ENDIF
10    CONTINUE
      IF (SP.GT.0) THEN
        PRINT *,'AVERAGE WEIGHT IS',SW/SP
      ELSE
        PRINT *,'THERE ARE NO MEN AGED BETWEEN 21 AND 35'
      ENDIF
      END
