C RIDERS AT A CYCLE RACE ARE DIVIDED IN TWO RACES
C BASED UPON AN INITIAL TIME TRIAL
C A PROGRAM READS DATA FOR EACH RIDERS
C CONSISTING OF THE RIDER'S NUMBER AND HIS TIME
C AND PRINTS A LIST GIVING THE NUMBER AND THE RACE
C (A OR B) TO WHICH HAS BEEN ALLOCATED: IF HIS
C TIME IS LESS THAN 1 MINUTE 50 S FOR THE TRIAL
C HE SHOULD BE IN RACE A OTHERWISE IN RACE B
C THE DATA WILL BE TERMINATED BY A RIDER WITH NEGATIVE TIME
C 1 INITIALISE VARIABLES
C 2 REPEAT THE FOLLOWING
C    2.1 READ A NUMBER AND A TIME IN SECONDS
C    2.2 IF TIME IS NEGATIVE THEN EXIT THE LOOP
C    2.3 PRINT LIST ITEM    
C 3 END

      PROGRAM CYCLES
        INTEGER NUM,TIME
10    PRINT *,'READING NUMBER AND TRIAL TIME'
      READ *,NUM,TIME
      IF (TIME.LT.0) THEN
        GOTO 20
      ELSE IF ((TIME.GE.0.).AND.(TIME.LT.110)) THEN
        PRINT *,NUM,'A'
      ELSE
        PRINT *,NUM,'B'
      ENDIF
      GOTO 10
20    PRINT *,'LIST END'
      STOP
      END
