C THIS PROGRAM READS 4 INTEGERS AND PRINT THE DIFFERENCE
C BETWEEN THE SUM OF THE FIRST TWO AND THE SUM
C OF THE LAST TWO
       PROGRAM DIFFSUM
        INTEGER R1,R2,R3,R4,SUM1,SUM2,DIFF
        PRINT *,'EXPECTING YOU TO ENTER 4 INTEGERS'
        PRINT *,'PLEASE ENTER THE INTEGER N.1'
        READ *,R1
        PRINT *,'PLEASE ENTER THE INTEGER N.2'
        READ *,R2
        SUM1 = R1 + R2
        PRINT *,'PLEASE ENTER THE INTEGER N.3'
        READ *,R3
        PRINT *,'PLEASE ENTER THE INTEGER N.4'
        READ *,R4
        SUM2 = R3 + R4
        DIFF = SUM1 - SUM2
        PRINT *,'THE DIFFERENCE SUM1 - SUM2 IS',DIFF
       END
